### ISSUE TITLE
App doesnt start in production

### ISSUE THREAD

**Issue by markieo1** [GiethoornInternationalHarbor/RefuelService#2]
>  Unhandled Exception: System.ArgumentNullException: Value cannot be null.
2018-05-22T15:51:06.003449187Z giethoorninternationalharbor_refuel.1.nlc37lm68wwo@giethoorn-docker-droplet    | Parameter name: uriString
2018-05-22T15:51:06.003454627Z giethoorninternationalharbor_refuel.1.nlc37lm68wwo@giethoorn-docker-droplet    |    at System.Uri..ctor(String uriString)
2018-05-22T15:51:06.003480617Z giethoorninternationalharbor_refuel.1.nlc37lm68wwo@giethoorn-docker-droplet    |    at RefuelService.Infrastructure.DI.DIHelper.<>c__DisplayClass0_0.<Setup>b__1(IServiceProvider provider) in /app/RefuelService.Infrastructure/DI/DIHelper.cs:line 24
2018-05-22T15:51:06.003492746Z giethoorninternationalharbor_refuel.1.nlc37lm68wwo@giethoorn-docker-droplet    |    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProvider provider)
2018-05-22T15:51:06.003497022Z giethoorninternationalharbor_refuel.1.nlc37lm68wwo@giethoorn-docker-droplet    |    at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
2018-05-22T15:51:06.003501788Z giethoorninternationalharbor_refuel.1.nlc37lm68wwo@giethoorn-docker-droplet    |    at RefuelService.App.Program.Main(String[] args) in /app/RefuelService.App/Program.cs:line 52

**Comment by markieo1** [comment]
Use the environment variable: `AMQP_URL` instead

**Comment by Daan298261** [comment]
fixed in designated hotfixes
